name: generate_clone
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo


environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  http: ^1.2.2

  archive: ^3.6.1
  rename: ^3.0.2
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.0


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
