name: generate_clone
description: A starting point for Dart libraries or applications.
version: 1.0.1
# repository: https://github.com/my_org/my_repo
executables:
  generate_clone: generate_clone

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  http: ^1.3.0

  archive: ^4.0.2



dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
