name: generate_clone
description: A CLI tool for generating Flutter app clones with dynamic configuration, supporting local directories, ZIP files, and remote URLs.
version: 1.0.3
repository: https://github.com/abdullahzreqat/generate_clone
homepage: https://github.com/abdullahzreqat/generate_clone

executables:
  generate_clone: generate_clone

environment:
  sdk: ^3.4.4

dependencies:
  path: ^1.9.1
  http: ^1.6.0
  archive: ^4.0.7

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
