name: generate_clone
description: A CLI tool for generating Flutter app clones with dynamic configuration, supporting local directories, ZIP files, and remote URLs.
version: 1.0.2
repository: https://github.com/abdullahzreqat/generate_clone
homepage: https://github.com/abdullahzreqat/generate_clone

executables:
  generate_clone: generate_clone

environment:
  sdk: ^3.4.4

dependencies:
  path: ^1.9.0
  http: ^1.3.0
  archive: ^4.0.2

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
